version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: user-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mangalam
      POSTGRES_PASSWORD: mangalam
      POSTGRES_DB: user_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
